### ISSUE TITLE
get_association_region.py missing

### ISSUE THREAD

**Issue by marusazerjal** [mikeireland/chronostar#3]
It seems that we deleted a bit too much when separating Chronostar and Individual projects.

**Comment by marusazerjal** [comment]
I copied `get_association_region.py` back into `scripts` for now.
But I am not sure if this is a good location for the future.

**Comment by marusazerjal** [comment]
I hardcoded `gagne_reference_data` in the script since the data file is not tracked and only available in your home folder.

**Comment by tcrundall** [comment]
Hi Marusa,
Thank you for bringing this to my attention. I will work on reincorporating all necessary files into Chronostar.

**Comment by tcrundall** [comment]
The function get_region is now part of a chronostar module `datatool`. I've updated `run_chronostar.py` to reflect this change. If one wishes to use the `get_region`, then the config file must have:
```
config = {
  'assoc_ref_table':'path/to/table/eg/gagne/table,
  'assoc_name':'some_moving_group_name',          # this must appear in column `mg_colname` of ref_table
  'mg_colname':'colname_in_table',          # defaults to 'Moving group', which is Banyan's colname
}
```
@marusazerjal I'm not a fan of keeping track of a data file via git, which is why `gagne_reference_data` wasn't there. Do you think we should? Or is it fine to expect the user to provide their own table of membership stars?

**Comment by tcrundall** [comment]
Upon discussions with Marusa I've determined this issue as closed.
